/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.apache.commons.text.StringSubstitutor;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String getSystemReport() {
        return StringSubstitutor.replaceSystemProperties(
            "You are running with java.version = ${java.version} and os.name = ${os.name}."
        );
    }
}
